### ISSUE TITLE
Covid vaccines in GOLD 202307

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/cdm-etl-gold#21]
**Describe the problem**
Hi @teenwyman in the previous release (gold_202301) we had millions of records of covid vaccines, now when we instantiate the same cohorts in the new release (gold_202307) they are empty.
Has the mapping changed?
thank youuu :)

**Affected databases**
cprd_gold_202307

**Tag for awareness**
@ajoedicke @Xintong-Li-ZnCu

**Comment by teenwyman** [comment]
@catalamarti 
Thank you for finding the bug in the ETL program. 
As discussed, data patching is required, and it is ongoing. I will update you once it is completed.

Here are some findings for your reference.
In **cdm_gold_202301**, the following read codes have been used for mapping the covid-19 vaccination brand name. 
Read Code | Description
-- | --
65F0100 | Administration of first dose of severe acute respiratory syndrome   coronavirus 2 vaccine (procedure) (SNOMED CT Concept 1324681000000101)
65F0200 | Administration of second dose of severe acute respiratory syndrome   coronavirus 2 vaccine (procedure) (SNOMED CT Concept 1324691000000104)
65F0900 | Administration of third dose of severe acute respiratory syndrome   coronavirus 2 vaccine (procedure) (SNOMED CT Concept 1363861000000103)
65F0A00 | Administration of fourth dose of severe acute respiratory syndrome   coronavirus 2 vaccine (procedure) (SNOMED CT Concept 1363791000000101)
65F0B00 | Administration of fifth dose of severe acute respiratory syndrome   coronavirus 2 vaccine (procedure) (SNOMED CT Concept 1363831000000108)
-------------------
In **cdm_gold_202307**, more read codes have been taken into account. 
You can find all read codes and brands (COVID Immunisation Types) we used for COVID-19 Vaccination [here](https://help.cegedim-healthcare.co.uk/Coronavirus_guidance/Content/Coronavirus_Guidance/Vaccinations.htm) 
However, 

- COVID - Medicago (Previously COVID-19 – Medicago) is NOT found in GOLD. 
- No COVID Immunisation Types are recorded in GOLD for 65F0300, 65F0400, 65F0500
- Athena maps [65F0300](https://athena.ohdsi.org/search-terms/terms/940618), [65F0400](https://athena.ohdsi.org/search-terms/terms/940619), [65F0500](https://athena.ohdsi.org/search-terms/terms/940620) to [37003432](https://athena.ohdsi.org/search-terms/terms/37003432)

**Comment by teenwyman** [comment]
Fixed.

**Comment by teenwyman** [comment]
Fixed.
