### ISSUE TITLE
[Mapping issue] Why is 4214962 in condition occurrence?

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/cdm-etl-gold#23]
**Describe the problem**
- One of the most common codes (15% in a sample I took) in the condition occurrence table is "Blood pressure finding" 4214962 https://athena.ohdsi.org/search-terms/terms/4214962. Should this information instead be in the measurement table, ideally with the value? 

**Affected databases**
cdm_gold_202301 

**Tag for awareness**
@ajoedicke @daniprietoalhambra

**Comment by daniprietoalhambra** [comment]
That would be ideal


On 13 Feb 2024, at 15:22, edward-burn ***@***.***> wrote:

﻿

Describe the problem

  *   One of the most common codes (15% in a sample I took) in the condition occurrence table is "Blood pressure finding" 4214962 https://athena.ohdsi.org/search-terms/terms/4214962. Should this information instead be in the measurement table, ideally with the value?

Affected databases
cdm_gold_202301

Tag for awareness
@ajoedicke<https://github.com/ajoedicke> @daniprietoalhambra<https://github.com/daniprietoalhambra>

**Comment by teenwyman** [comment]
@edward-burn 

I use **public_100k** as an example. 

These conditon_occurrence records were mapped from the following Read Codes.
And the mapping is provided by Athena.  
condition_concept_id | condition_source_value (in public_100k) | count (in public_100k)
-- | -- | --
4214962 | [246..11](https://athena.ohdsi.org/search-terms/terms/45458327) | 55146
4214962 | [246..12](https://athena.ohdsi.org/search-terms/terms/45495071) | 3657
4214962 | [246Z.00](https://athena.ohdsi.org/search-terms/terms/45521684) | 189
4214962 | [246..00](https://athena.ohdsi.org/search-terms/terms/45471867) | 510087
