### ISSUE TITLE
[Mapping issue] Unmapped condition concepts

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/cdm-etl-gold#24]
**Describe the problem**
- Around 7% of condition concepts are mapped to 0, with the most frequent source codes for these being 9c0C.00, ZZZZZ00, and 9D1..00 which suggest these are not really condition occurrence records. I don´t think we need to keep these types of records as they won´t be used in any studies and removing them would make the table smaller and queries quicker.

**Affected databases**
cdm_gold_202301 

**Tag for awareness**
Not sure what you think @ajoedicke @daniprietoalhambra ?

**Comment by daniprietoalhambra** [comment]
Agreed, we could get rid of these



On 13 Feb 2024, at 15:31, edward-burn ***@***.***> wrote:

﻿

Describe the problem

  *   Around 7% of condition concepts are mapped to 0, with the most frequent source codes for these being 9c0C.00, ZZZZZ00, and 9D1..00 which suggest these are not really condition occurrence records. I don´t think we need to keep these types of records as they won´t be used in any studies and removing them would make the table smaller and queries quicker.

Affected databases
cdm_gold_202301

Tag for awareness
Not sure what you think @ajoedicke<https://github.com/ajoedicke> @daniprietoalhambra<https://github.com/daniprietoalhambra> ?

**Comment by ajoedicke** [comment]
Yes, we dont need these I think
________________________________

**Comment by teenwyman** [comment]
The ETL program will be updated. All condition_occurrence records with non-condition concept IDs will not exist in the next release (202401).

**Comment by daniprietoalhambra** [comment]
[heart]         Daniel Prieto Alhambra reacted to your message:
________________________________
