### ISSUE TITLE
[Mapping issue] mapping concept 44807962 as observation

### ISSUE THREAD

**Issue by nmercadeb** [oxford-pharmacoepi/cdm-etl-gold#34]
**Describe the problem**
@daniellenewby created a phenotype for breast cancer, and one of the concepts used was 44807962. The phenotype treated this concept as an observation event (in Athena its domain is observation), but we realised we were not picking up these events and we think it is because in CPRD Gold this concept is mapped in the procedure domain (see screenshot below). 

![cf55e933-2d88-45df-8428-a0ecdbf15aa2](https://github.com/oxford-pharmacoepi/cdm-etl-gold/assets/61558739/c81cd9a4-85d6-4716-94fc-b08c28ae4120)

See concept in Athena where the domain is Observation: https://athena.ohdsi.org/search-terms/terms/44807962

**Affected databases**
CPRD Gold 202307

**Comment by teenwyman** [comment]
@nmercadeb 
cdm_gold_202307 uses Athena vocabulary v5.0 31-AUG-23, in which Athena defines the concept 44807962, as a Procedure concept and maps it to itself. 
![image](https://github.com/user-attachments/assets/fea033b8-0c69-49cb-baf2-bbedd273b0c1)
![image](https://github.com/user-attachments/assets/46de4c83-27f0-4767-bf2e-abf7c1ad8493)

Athena keeps updating vocabularies. Domain change is a common one.

**Comment by nmercadeb** [comment]
Thank you @teenwyman !
